# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bytes Tying
email: stevzhg+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Draw an awesome path for coding here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asfork.github.io" # the base hostname & protocol for your site
twitter_username: sourcepanic 
github_username:  bytess 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-62121389-1
disqus_shortname: unpin

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
